[Modular_Basic]
_model_ = "./models/modular2x2.modest"
_output_ = "./tmp.csv"
CLK_UPPER = "1:1:12"

[Modular_Fixed]
_model_ = "./models/modular2x2error.modest"
_output_ = "./tmp1.csv"
CLK_UPPER = "1:1:12"

[Modular_Reward]
_model_ = "./models/modular2x2-reward.modest"
_output_ = "./tmp2.csv"
CLK_UPPER = "12:1:12"